name: Continuous Stream Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies & Setup Impersonate
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install "yt-dlp[default]" "curl_cffi>=0.5.10"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Main Script
        run: python main.py
